INSERT INTO rating VALUES (1,7,7,'good','good');
INSERT INTO rating VALUES (2,8,8,'nice','nice');
INSERT INTO rating VALUES (3,9,9,'great','great');
INSERT INTO rating VALUES (4,8,8,'perfect','perfect');
INSERT INTO rating (order_id, receiver_to_sender_rate, reveiver_to_rest_rate) VALUES (5,10,10);
INSERT INTO rating VALUES (6,3,3,'bad','bad');
INSERT INTO rating VALUES (7,2,8,'slow','delicious');
INSERT INTO rating VALUES (8,10,10,'hello','world');
INSERT INTO rating VALUES (9,10,10,'very fast','yummy');
INSERT INTO rating (order_id, receiver_to_sender_rate, reveiver_to_rest_rate) VALUES (10,5,5);
INSERT INTO rating (order_id, receiver_to_sender_rate, reveiver_to_rest_rate) VALUES (11,9,2);