// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Restaurant.proto

package com.feedr.protobuf;

public final class FoodProto {
  private FoodProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FoodOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Food)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string res_username = 1;</code>
     */
    java.lang.String getResUsername();
    /**
     * <code>optional string res_username = 1;</code>
     */
    com.google.protobuf.ByteString
        getResUsernameBytes();

    /**
     * <code>optional string foodname = 2;</code>
     */
    java.lang.String getFoodname();
    /**
     * <code>optional string foodname = 2;</code>
     */
    com.google.protobuf.ByteString
        getFoodnameBytes();

    /**
     * <code>optional double price = 3;</code>
     */
    double getPrice();

    /**
     * <code>optional string type = 4;</code>
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 4;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     *only used when querying for orders
     * </pre>
     *
     * <code>optional int32 quantity = 5;</code>
     */
    int getQuantity();
  }
  /**
   * Protobuf type {@code Food}
   */
  public  static final class Food extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Food)
      FoodOrBuilder {
    // Use Food.newBuilder() to construct.
    private Food(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Food() {
      resUsername_ = "";
      foodname_ = "";
      price_ = 0D;
      type_ = "";
      quantity_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Food(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              resUsername_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              foodname_ = s;
              break;
            }
            case 25: {

              price_ = input.readDouble();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 40: {

              quantity_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.feedr.protobuf.FoodProto.internal_static_Food_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.feedr.protobuf.FoodProto.internal_static_Food_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.feedr.protobuf.FoodProto.Food.class, com.feedr.protobuf.FoodProto.Food.Builder.class);
    }

    public static final int RES_USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object resUsername_;
    /**
     * <code>optional string res_username = 1;</code>
     */
    public java.lang.String getResUsername() {
      java.lang.Object ref = resUsername_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resUsername_ = s;
        return s;
      }
    }
    /**
     * <code>optional string res_username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResUsernameBytes() {
      java.lang.Object ref = resUsername_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FOODNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object foodname_;
    /**
     * <code>optional string foodname = 2;</code>
     */
    public java.lang.String getFoodname() {
      java.lang.Object ref = foodname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foodname_ = s;
        return s;
      }
    }
    /**
     * <code>optional string foodname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFoodnameBytes() {
      java.lang.Object ref = foodname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foodname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    private double price_;
    /**
     * <code>optional double price = 3;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object type_;
    /**
     * <code>optional string type = 4;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>optional string type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 5;
    private int quantity_;
    /**
     * <pre>
     *only used when querying for orders
     * </pre>
     *
     * <code>optional int32 quantity = 5;</code>
     */
    public int getQuantity() {
      return quantity_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resUsername_);
      }
      if (!getFoodnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, foodname_);
      }
      if (price_ != 0D) {
        output.writeDouble(3, price_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, type_);
      }
      if (quantity_ != 0) {
        output.writeInt32(5, quantity_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resUsername_);
      }
      if (!getFoodnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, foodname_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, price_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, type_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, quantity_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.feedr.protobuf.FoodProto.Food)) {
        return super.equals(obj);
      }
      com.feedr.protobuf.FoodProto.Food other = (com.feedr.protobuf.FoodProto.Food) obj;

      boolean result = true;
      result = result && getResUsername()
          .equals(other.getResUsername());
      result = result && getFoodname()
          .equals(other.getFoodname());
      result = result && (
          java.lang.Double.doubleToLongBits(getPrice())
          == java.lang.Double.doubleToLongBits(
              other.getPrice()));
      result = result && getType()
          .equals(other.getType());
      result = result && (getQuantity()
          == other.getQuantity());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RES_USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getResUsername().hashCode();
      hash = (37 * hash) + FOODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFoodname().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.feedr.protobuf.FoodProto.Food parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feedr.protobuf.FoodProto.Food parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feedr.protobuf.FoodProto.Food parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feedr.protobuf.FoodProto.Food parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feedr.protobuf.FoodProto.Food parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.FoodProto.Food parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feedr.protobuf.FoodProto.Food parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.FoodProto.Food parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feedr.protobuf.FoodProto.Food parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.FoodProto.Food parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.feedr.protobuf.FoodProto.Food prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Food}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Food)
        com.feedr.protobuf.FoodProto.FoodOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.feedr.protobuf.FoodProto.internal_static_Food_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.feedr.protobuf.FoodProto.internal_static_Food_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.feedr.protobuf.FoodProto.Food.class, com.feedr.protobuf.FoodProto.Food.Builder.class);
      }

      // Construct using com.feedr.protobuf.FoodProto.Food.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        resUsername_ = "";

        foodname_ = "";

        price_ = 0D;

        type_ = "";

        quantity_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.feedr.protobuf.FoodProto.internal_static_Food_descriptor;
      }

      public com.feedr.protobuf.FoodProto.Food getDefaultInstanceForType() {
        return com.feedr.protobuf.FoodProto.Food.getDefaultInstance();
      }

      public com.feedr.protobuf.FoodProto.Food build() {
        com.feedr.protobuf.FoodProto.Food result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.feedr.protobuf.FoodProto.Food buildPartial() {
        com.feedr.protobuf.FoodProto.Food result = new com.feedr.protobuf.FoodProto.Food(this);
        result.resUsername_ = resUsername_;
        result.foodname_ = foodname_;
        result.price_ = price_;
        result.type_ = type_;
        result.quantity_ = quantity_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.feedr.protobuf.FoodProto.Food) {
          return mergeFrom((com.feedr.protobuf.FoodProto.Food)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.feedr.protobuf.FoodProto.Food other) {
        if (other == com.feedr.protobuf.FoodProto.Food.getDefaultInstance()) return this;
        if (!other.getResUsername().isEmpty()) {
          resUsername_ = other.resUsername_;
          onChanged();
        }
        if (!other.getFoodname().isEmpty()) {
          foodname_ = other.foodname_;
          onChanged();
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.feedr.protobuf.FoodProto.Food parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.feedr.protobuf.FoodProto.Food) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object resUsername_ = "";
      /**
       * <code>optional string res_username = 1;</code>
       */
      public java.lang.String getResUsername() {
        java.lang.Object ref = resUsername_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resUsername_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string res_username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResUsernameBytes() {
        java.lang.Object ref = resUsername_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resUsername_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string res_username = 1;</code>
       */
      public Builder setResUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resUsername_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string res_username = 1;</code>
       */
      public Builder clearResUsername() {
        
        resUsername_ = getDefaultInstance().getResUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string res_username = 1;</code>
       */
      public Builder setResUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resUsername_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object foodname_ = "";
      /**
       * <code>optional string foodname = 2;</code>
       */
      public java.lang.String getFoodname() {
        java.lang.Object ref = foodname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          foodname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string foodname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFoodnameBytes() {
        java.lang.Object ref = foodname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          foodname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string foodname = 2;</code>
       */
      public Builder setFoodname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        foodname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string foodname = 2;</code>
       */
      public Builder clearFoodname() {
        
        foodname_ = getDefaultInstance().getFoodname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string foodname = 2;</code>
       */
      public Builder setFoodnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        foodname_ = value;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>optional double price = 3;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>optional double price = 3;</code>
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double price = 3;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 4;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 4;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 4;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <pre>
       *only used when querying for orders
       * </pre>
       *
       * <code>optional int32 quantity = 5;</code>
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <pre>
       *only used when querying for orders
       * </pre>
       *
       * <code>optional int32 quantity = 5;</code>
       */
      public Builder setQuantity(int value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *only used when querying for orders
       * </pre>
       *
       * <code>optional int32 quantity = 5;</code>
       */
      public Builder clearQuantity() {
        
        quantity_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Food)
    }

    // @@protoc_insertion_point(class_scope:Food)
    private static final com.feedr.protobuf.FoodProto.Food DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.feedr.protobuf.FoodProto.Food();
    }

    public static com.feedr.protobuf.FoodProto.Food getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Food>
        PARSER = new com.google.protobuf.AbstractParser<Food>() {
      public Food parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Food(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Food> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Food> getParserForType() {
      return PARSER;
    }

    public com.feedr.protobuf.FoodProto.Food getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Food_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Food_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Restaurant.proto\"]\n\004Food\022\024\n\014res_userna" +
      "me\030\001 \001(\t\022\020\n\010foodname\030\002 \001(\t\022\r\n\005price\030\003 \001(" +
      "\001\022\014\n\004type\030\004 \001(\t\022\020\n\010quantity\030\005 \001(\005B\037\n\022com" +
      ".feedr.protobufB\tFoodProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Food_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Food_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Food_descriptor,
        new java.lang.String[] { "ResUsername", "Foodname", "Price", "Type", "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
