// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Order.proto

package com.feedr.protobuf;

public final class OrderProto {
  private OrderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 order_id = 1;</code>
     */
    int getOrderId();

    /**
     * <code>optional string sender_name = 2;</code>
     */
    java.lang.String getSenderName();
    /**
     * <code>optional string sender_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getSenderNameBytes();

    /**
     * <code>optional string receiver_name = 3;</code>
     */
    java.lang.String getReceiverName();
    /**
     * <code>optional string receiver_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getReceiverNameBytes();

    /**
     * <code>optional string restaurant_name = 4;</code>
     */
    java.lang.String getRestaurantName();
    /**
     * <code>optional string restaurant_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getRestaurantNameBytes();

    /**
     * <code>optional double order_cost = 5;</code>
     */
    double getOrderCost();

    /**
     * <code>optional double deliver_tip = 6;</code>
     */
    double getDeliverTip();

    /**
     * <code>optional string order_time = 7;</code>
     */
    java.lang.String getOrderTime();
    /**
     * <code>optional string order_time = 7;</code>
     */
    com.google.protobuf.ByteString
        getOrderTimeBytes();

    /**
     * <pre>
     *frontend generate datetime format
     * </pre>
     *
     * <code>optional string deadline = 8;</code>
     */
    java.lang.String getDeadline();
    /**
     * <pre>
     *frontend generate datetime format
     * </pre>
     *
     * <code>optional string deadline = 8;</code>
     */
    com.google.protobuf.ByteString
        getDeadlineBytes();

    /**
     * <code>optional string delivery_location = 9;</code>
     */
    java.lang.String getDeliveryLocation();
    /**
     * <code>optional string delivery_location = 9;</code>
     */
    com.google.protobuf.ByteString
        getDeliveryLocationBytes();

    /**
     * <code>optional string phone = 10;</code>
     */
    java.lang.String getPhone();
    /**
     * <code>optional string phone = 10;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>optional bool canceled = 11;</code>
     */
    boolean getCanceled();

    /**
     * <code>optional bool delivered = 12;</code>
     */
    boolean getDelivered();

    /**
     * <code>repeated .Food foodMap = 13;</code>
     */
    java.util.List<com.feedr.protobuf.FoodProto.Food> 
        getFoodMapList();
    /**
     * <code>repeated .Food foodMap = 13;</code>
     */
    com.feedr.protobuf.FoodProto.Food getFoodMap(int index);
    /**
     * <code>repeated .Food foodMap = 13;</code>
     */
    int getFoodMapCount();
    /**
     * <code>repeated .Food foodMap = 13;</code>
     */
    java.util.List<? extends com.feedr.protobuf.FoodProto.FoodOrBuilder> 
        getFoodMapOrBuilderList();
    /**
     * <code>repeated .Food foodMap = 13;</code>
     */
    com.feedr.protobuf.FoodProto.FoodOrBuilder getFoodMapOrBuilder(
        int index);

    /**
     * <code>optional string cancelReason = 14;</code>
     */
    java.lang.String getCancelReason();
    /**
     * <code>optional string cancelReason = 14;</code>
     */
    com.google.protobuf.ByteString
        getCancelReasonBytes();
  }
  /**
   * Protobuf type {@code Order}
   */
  public  static final class Order extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Order)
      OrderOrBuilder {
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Order() {
      orderId_ = 0;
      senderName_ = "";
      receiverName_ = "";
      restaurantName_ = "";
      orderCost_ = 0D;
      deliverTip_ = 0D;
      orderTime_ = "";
      deadline_ = "";
      deliveryLocation_ = "";
      phone_ = "";
      canceled_ = false;
      delivered_ = false;
      foodMap_ = java.util.Collections.emptyList();
      cancelReason_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Order(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              orderId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              senderName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              restaurantName_ = s;
              break;
            }
            case 41: {

              orderCost_ = input.readDouble();
              break;
            }
            case 49: {

              deliverTip_ = input.readDouble();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              orderTime_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              deadline_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              deliveryLocation_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
            case 88: {

              canceled_ = input.readBool();
              break;
            }
            case 96: {

              delivered_ = input.readBool();
              break;
            }
            case 106: {
              if (!((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
                foodMap_ = new java.util.ArrayList<com.feedr.protobuf.FoodProto.Food>();
                mutable_bitField0_ |= 0x00001000;
              }
              foodMap_.add(
                  input.readMessage(com.feedr.protobuf.FoodProto.Food.parser(), extensionRegistry));
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              cancelReason_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
          foodMap_ = java.util.Collections.unmodifiableList(foodMap_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.feedr.protobuf.OrderProto.internal_static_Order_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.feedr.protobuf.OrderProto.internal_static_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.feedr.protobuf.OrderProto.Order.class, com.feedr.protobuf.OrderProto.Order.Builder.class);
    }

    private int bitField0_;
    public static final int ORDER_ID_FIELD_NUMBER = 1;
    private int orderId_;
    /**
     * <code>optional int32 order_id = 1;</code>
     */
    public int getOrderId() {
      return orderId_;
    }

    public static final int SENDER_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object senderName_;
    /**
     * <code>optional string sender_name = 2;</code>
     */
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sender_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object receiverName_;
    /**
     * <code>optional string receiver_name = 3;</code>
     */
    public java.lang.String getReceiverName() {
      java.lang.Object ref = receiverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string receiver_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverNameBytes() {
      java.lang.Object ref = receiverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESTAURANT_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object restaurantName_;
    /**
     * <code>optional string restaurant_name = 4;</code>
     */
    public java.lang.String getRestaurantName() {
      java.lang.Object ref = restaurantName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        restaurantName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string restaurant_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRestaurantNameBytes() {
      java.lang.Object ref = restaurantName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        restaurantName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDER_COST_FIELD_NUMBER = 5;
    private double orderCost_;
    /**
     * <code>optional double order_cost = 5;</code>
     */
    public double getOrderCost() {
      return orderCost_;
    }

    public static final int DELIVER_TIP_FIELD_NUMBER = 6;
    private double deliverTip_;
    /**
     * <code>optional double deliver_tip = 6;</code>
     */
    public double getDeliverTip() {
      return deliverTip_;
    }

    public static final int ORDER_TIME_FIELD_NUMBER = 7;
    private volatile java.lang.Object orderTime_;
    /**
     * <code>optional string order_time = 7;</code>
     */
    public java.lang.String getOrderTime() {
      java.lang.Object ref = orderTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string order_time = 7;</code>
     */
    public com.google.protobuf.ByteString
        getOrderTimeBytes() {
      java.lang.Object ref = orderTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEADLINE_FIELD_NUMBER = 8;
    private volatile java.lang.Object deadline_;
    /**
     * <pre>
     *frontend generate datetime format
     * </pre>
     *
     * <code>optional string deadline = 8;</code>
     */
    public java.lang.String getDeadline() {
      java.lang.Object ref = deadline_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deadline_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *frontend generate datetime format
     * </pre>
     *
     * <code>optional string deadline = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDeadlineBytes() {
      java.lang.Object ref = deadline_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deadline_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELIVERY_LOCATION_FIELD_NUMBER = 9;
    private volatile java.lang.Object deliveryLocation_;
    /**
     * <code>optional string delivery_location = 9;</code>
     */
    public java.lang.String getDeliveryLocation() {
      java.lang.Object ref = deliveryLocation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deliveryLocation_ = s;
        return s;
      }
    }
    /**
     * <code>optional string delivery_location = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDeliveryLocationBytes() {
      java.lang.Object ref = deliveryLocation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deliveryLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 10;
    private volatile java.lang.Object phone_;
    /**
     * <code>optional string phone = 10;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>optional string phone = 10;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CANCELED_FIELD_NUMBER = 11;
    private boolean canceled_;
    /**
     * <code>optional bool canceled = 11;</code>
     */
    public boolean getCanceled() {
      return canceled_;
    }

    public static final int DELIVERED_FIELD_NUMBER = 12;
    private boolean delivered_;
    /**
     * <code>optional bool delivered = 12;</code>
     */
    public boolean getDelivered() {
      return delivered_;
    }

    public static final int FOODMAP_FIELD_NUMBER = 13;
    private java.util.List<com.feedr.protobuf.FoodProto.Food> foodMap_;
    /**
     * <code>repeated .Food foodMap = 13;</code>
     */
    public java.util.List<com.feedr.protobuf.FoodProto.Food> getFoodMapList() {
      return foodMap_;
    }
    /**
     * <code>repeated .Food foodMap = 13;</code>
     */
    public java.util.List<? extends com.feedr.protobuf.FoodProto.FoodOrBuilder> 
        getFoodMapOrBuilderList() {
      return foodMap_;
    }
    /**
     * <code>repeated .Food foodMap = 13;</code>
     */
    public int getFoodMapCount() {
      return foodMap_.size();
    }
    /**
     * <code>repeated .Food foodMap = 13;</code>
     */
    public com.feedr.protobuf.FoodProto.Food getFoodMap(int index) {
      return foodMap_.get(index);
    }
    /**
     * <code>repeated .Food foodMap = 13;</code>
     */
    public com.feedr.protobuf.FoodProto.FoodOrBuilder getFoodMapOrBuilder(
        int index) {
      return foodMap_.get(index);
    }

    public static final int CANCELREASON_FIELD_NUMBER = 14;
    private volatile java.lang.Object cancelReason_;
    /**
     * <code>optional string cancelReason = 14;</code>
     */
    public java.lang.String getCancelReason() {
      java.lang.Object ref = cancelReason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cancelReason_ = s;
        return s;
      }
    }
    /**
     * <code>optional string cancelReason = 14;</code>
     */
    public com.google.protobuf.ByteString
        getCancelReasonBytes() {
      java.lang.Object ref = cancelReason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cancelReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (orderId_ != 0) {
        output.writeInt32(1, orderId_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderName_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, receiverName_);
      }
      if (!getRestaurantNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, restaurantName_);
      }
      if (orderCost_ != 0D) {
        output.writeDouble(5, orderCost_);
      }
      if (deliverTip_ != 0D) {
        output.writeDouble(6, deliverTip_);
      }
      if (!getOrderTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, orderTime_);
      }
      if (!getDeadlineBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, deadline_);
      }
      if (!getDeliveryLocationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, deliveryLocation_);
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, phone_);
      }
      if (canceled_ != false) {
        output.writeBool(11, canceled_);
      }
      if (delivered_ != false) {
        output.writeBool(12, delivered_);
      }
      for (int i = 0; i < foodMap_.size(); i++) {
        output.writeMessage(13, foodMap_.get(i));
      }
      if (!getCancelReasonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, cancelReason_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (orderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, orderId_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderName_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, receiverName_);
      }
      if (!getRestaurantNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, restaurantName_);
      }
      if (orderCost_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, orderCost_);
      }
      if (deliverTip_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, deliverTip_);
      }
      if (!getOrderTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, orderTime_);
      }
      if (!getDeadlineBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, deadline_);
      }
      if (!getDeliveryLocationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, deliveryLocation_);
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, phone_);
      }
      if (canceled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, canceled_);
      }
      if (delivered_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, delivered_);
      }
      for (int i = 0; i < foodMap_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, foodMap_.get(i));
      }
      if (!getCancelReasonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, cancelReason_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.feedr.protobuf.OrderProto.Order)) {
        return super.equals(obj);
      }
      com.feedr.protobuf.OrderProto.Order other = (com.feedr.protobuf.OrderProto.Order) obj;

      boolean result = true;
      result = result && (getOrderId()
          == other.getOrderId());
      result = result && getSenderName()
          .equals(other.getSenderName());
      result = result && getReceiverName()
          .equals(other.getReceiverName());
      result = result && getRestaurantName()
          .equals(other.getRestaurantName());
      result = result && (
          java.lang.Double.doubleToLongBits(getOrderCost())
          == java.lang.Double.doubleToLongBits(
              other.getOrderCost()));
      result = result && (
          java.lang.Double.doubleToLongBits(getDeliverTip())
          == java.lang.Double.doubleToLongBits(
              other.getDeliverTip()));
      result = result && getOrderTime()
          .equals(other.getOrderTime());
      result = result && getDeadline()
          .equals(other.getDeadline());
      result = result && getDeliveryLocation()
          .equals(other.getDeliveryLocation());
      result = result && getPhone()
          .equals(other.getPhone());
      result = result && (getCanceled()
          == other.getCanceled());
      result = result && (getDelivered()
          == other.getDelivered());
      result = result && getFoodMapList()
          .equals(other.getFoodMapList());
      result = result && getCancelReason()
          .equals(other.getCancelReason());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ORDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId();
      hash = (37 * hash) + SENDER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSenderName().hashCode();
      hash = (37 * hash) + RECEIVER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverName().hashCode();
      hash = (37 * hash) + RESTAURANT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getRestaurantName().hashCode();
      hash = (37 * hash) + ORDER_COST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getOrderCost()));
      hash = (37 * hash) + DELIVER_TIP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDeliverTip()));
      hash = (37 * hash) + ORDER_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getOrderTime().hashCode();
      hash = (37 * hash) + DEADLINE_FIELD_NUMBER;
      hash = (53 * hash) + getDeadline().hashCode();
      hash = (37 * hash) + DELIVERY_LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getDeliveryLocation().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + CANCELED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCanceled());
      hash = (37 * hash) + DELIVERED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDelivered());
      if (getFoodMapCount() > 0) {
        hash = (37 * hash) + FOODMAP_FIELD_NUMBER;
        hash = (53 * hash) + getFoodMapList().hashCode();
      }
      hash = (37 * hash) + CANCELREASON_FIELD_NUMBER;
      hash = (53 * hash) + getCancelReason().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.feedr.protobuf.OrderProto.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feedr.protobuf.OrderProto.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feedr.protobuf.OrderProto.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feedr.protobuf.OrderProto.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feedr.protobuf.OrderProto.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.OrderProto.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feedr.protobuf.OrderProto.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.OrderProto.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feedr.protobuf.OrderProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.OrderProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.feedr.protobuf.OrderProto.Order prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Order)
        com.feedr.protobuf.OrderProto.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.feedr.protobuf.OrderProto.internal_static_Order_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.feedr.protobuf.OrderProto.internal_static_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.feedr.protobuf.OrderProto.Order.class, com.feedr.protobuf.OrderProto.Order.Builder.class);
      }

      // Construct using com.feedr.protobuf.OrderProto.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFoodMapFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        orderId_ = 0;

        senderName_ = "";

        receiverName_ = "";

        restaurantName_ = "";

        orderCost_ = 0D;

        deliverTip_ = 0D;

        orderTime_ = "";

        deadline_ = "";

        deliveryLocation_ = "";

        phone_ = "";

        canceled_ = false;

        delivered_ = false;

        if (foodMapBuilder_ == null) {
          foodMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00001000);
        } else {
          foodMapBuilder_.clear();
        }
        cancelReason_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.feedr.protobuf.OrderProto.internal_static_Order_descriptor;
      }

      public com.feedr.protobuf.OrderProto.Order getDefaultInstanceForType() {
        return com.feedr.protobuf.OrderProto.Order.getDefaultInstance();
      }

      public com.feedr.protobuf.OrderProto.Order build() {
        com.feedr.protobuf.OrderProto.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.feedr.protobuf.OrderProto.Order buildPartial() {
        com.feedr.protobuf.OrderProto.Order result = new com.feedr.protobuf.OrderProto.Order(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.orderId_ = orderId_;
        result.senderName_ = senderName_;
        result.receiverName_ = receiverName_;
        result.restaurantName_ = restaurantName_;
        result.orderCost_ = orderCost_;
        result.deliverTip_ = deliverTip_;
        result.orderTime_ = orderTime_;
        result.deadline_ = deadline_;
        result.deliveryLocation_ = deliveryLocation_;
        result.phone_ = phone_;
        result.canceled_ = canceled_;
        result.delivered_ = delivered_;
        if (foodMapBuilder_ == null) {
          if (((bitField0_ & 0x00001000) == 0x00001000)) {
            foodMap_ = java.util.Collections.unmodifiableList(foodMap_);
            bitField0_ = (bitField0_ & ~0x00001000);
          }
          result.foodMap_ = foodMap_;
        } else {
          result.foodMap_ = foodMapBuilder_.build();
        }
        result.cancelReason_ = cancelReason_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.feedr.protobuf.OrderProto.Order) {
          return mergeFrom((com.feedr.protobuf.OrderProto.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.feedr.protobuf.OrderProto.Order other) {
        if (other == com.feedr.protobuf.OrderProto.Order.getDefaultInstance()) return this;
        if (other.getOrderId() != 0) {
          setOrderId(other.getOrderId());
        }
        if (!other.getSenderName().isEmpty()) {
          senderName_ = other.senderName_;
          onChanged();
        }
        if (!other.getReceiverName().isEmpty()) {
          receiverName_ = other.receiverName_;
          onChanged();
        }
        if (!other.getRestaurantName().isEmpty()) {
          restaurantName_ = other.restaurantName_;
          onChanged();
        }
        if (other.getOrderCost() != 0D) {
          setOrderCost(other.getOrderCost());
        }
        if (other.getDeliverTip() != 0D) {
          setDeliverTip(other.getDeliverTip());
        }
        if (!other.getOrderTime().isEmpty()) {
          orderTime_ = other.orderTime_;
          onChanged();
        }
        if (!other.getDeadline().isEmpty()) {
          deadline_ = other.deadline_;
          onChanged();
        }
        if (!other.getDeliveryLocation().isEmpty()) {
          deliveryLocation_ = other.deliveryLocation_;
          onChanged();
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        if (other.getCanceled() != false) {
          setCanceled(other.getCanceled());
        }
        if (other.getDelivered() != false) {
          setDelivered(other.getDelivered());
        }
        if (foodMapBuilder_ == null) {
          if (!other.foodMap_.isEmpty()) {
            if (foodMap_.isEmpty()) {
              foodMap_ = other.foodMap_;
              bitField0_ = (bitField0_ & ~0x00001000);
            } else {
              ensureFoodMapIsMutable();
              foodMap_.addAll(other.foodMap_);
            }
            onChanged();
          }
        } else {
          if (!other.foodMap_.isEmpty()) {
            if (foodMapBuilder_.isEmpty()) {
              foodMapBuilder_.dispose();
              foodMapBuilder_ = null;
              foodMap_ = other.foodMap_;
              bitField0_ = (bitField0_ & ~0x00001000);
              foodMapBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFoodMapFieldBuilder() : null;
            } else {
              foodMapBuilder_.addAllMessages(other.foodMap_);
            }
          }
        }
        if (!other.getCancelReason().isEmpty()) {
          cancelReason_ = other.cancelReason_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.feedr.protobuf.OrderProto.Order parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.feedr.protobuf.OrderProto.Order) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int orderId_ ;
      /**
       * <code>optional int32 order_id = 1;</code>
       */
      public int getOrderId() {
        return orderId_;
      }
      /**
       * <code>optional int32 order_id = 1;</code>
       */
      public Builder setOrderId(int value) {
        
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 order_id = 1;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object senderName_ = "";
      /**
       * <code>optional string sender_name = 2;</code>
       */
      public java.lang.String getSenderName() {
        java.lang.Object ref = senderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sender_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSenderNameBytes() {
        java.lang.Object ref = senderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sender_name = 2;</code>
       */
      public Builder setSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sender_name = 2;</code>
       */
      public Builder clearSenderName() {
        
        senderName_ = getDefaultInstance().getSenderName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sender_name = 2;</code>
       */
      public Builder setSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverName_ = "";
      /**
       * <code>optional string receiver_name = 3;</code>
       */
      public java.lang.String getReceiverName() {
        java.lang.Object ref = receiverName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string receiver_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverNameBytes() {
        java.lang.Object ref = receiverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string receiver_name = 3;</code>
       */
      public Builder setReceiverName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiver_name = 3;</code>
       */
      public Builder clearReceiverName() {
        
        receiverName_ = getDefaultInstance().getReceiverName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiver_name = 3;</code>
       */
      public Builder setReceiverNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object restaurantName_ = "";
      /**
       * <code>optional string restaurant_name = 4;</code>
       */
      public java.lang.String getRestaurantName() {
        java.lang.Object ref = restaurantName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          restaurantName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string restaurant_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRestaurantNameBytes() {
        java.lang.Object ref = restaurantName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          restaurantName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string restaurant_name = 4;</code>
       */
      public Builder setRestaurantName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        restaurantName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string restaurant_name = 4;</code>
       */
      public Builder clearRestaurantName() {
        
        restaurantName_ = getDefaultInstance().getRestaurantName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string restaurant_name = 4;</code>
       */
      public Builder setRestaurantNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        restaurantName_ = value;
        onChanged();
        return this;
      }

      private double orderCost_ ;
      /**
       * <code>optional double order_cost = 5;</code>
       */
      public double getOrderCost() {
        return orderCost_;
      }
      /**
       * <code>optional double order_cost = 5;</code>
       */
      public Builder setOrderCost(double value) {
        
        orderCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double order_cost = 5;</code>
       */
      public Builder clearOrderCost() {
        
        orderCost_ = 0D;
        onChanged();
        return this;
      }

      private double deliverTip_ ;
      /**
       * <code>optional double deliver_tip = 6;</code>
       */
      public double getDeliverTip() {
        return deliverTip_;
      }
      /**
       * <code>optional double deliver_tip = 6;</code>
       */
      public Builder setDeliverTip(double value) {
        
        deliverTip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double deliver_tip = 6;</code>
       */
      public Builder clearDeliverTip() {
        
        deliverTip_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object orderTime_ = "";
      /**
       * <code>optional string order_time = 7;</code>
       */
      public java.lang.String getOrderTime() {
        java.lang.Object ref = orderTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string order_time = 7;</code>
       */
      public com.google.protobuf.ByteString
          getOrderTimeBytes() {
        java.lang.Object ref = orderTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string order_time = 7;</code>
       */
      public Builder setOrderTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string order_time = 7;</code>
       */
      public Builder clearOrderTime() {
        
        orderTime_ = getDefaultInstance().getOrderTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string order_time = 7;</code>
       */
      public Builder setOrderTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deadline_ = "";
      /**
       * <pre>
       *frontend generate datetime format
       * </pre>
       *
       * <code>optional string deadline = 8;</code>
       */
      public java.lang.String getDeadline() {
        java.lang.Object ref = deadline_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deadline_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *frontend generate datetime format
       * </pre>
       *
       * <code>optional string deadline = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDeadlineBytes() {
        java.lang.Object ref = deadline_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deadline_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *frontend generate datetime format
       * </pre>
       *
       * <code>optional string deadline = 8;</code>
       */
      public Builder setDeadline(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deadline_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *frontend generate datetime format
       * </pre>
       *
       * <code>optional string deadline = 8;</code>
       */
      public Builder clearDeadline() {
        
        deadline_ = getDefaultInstance().getDeadline();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *frontend generate datetime format
       * </pre>
       *
       * <code>optional string deadline = 8;</code>
       */
      public Builder setDeadlineBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deadline_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deliveryLocation_ = "";
      /**
       * <code>optional string delivery_location = 9;</code>
       */
      public java.lang.String getDeliveryLocation() {
        java.lang.Object ref = deliveryLocation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deliveryLocation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string delivery_location = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDeliveryLocationBytes() {
        java.lang.Object ref = deliveryLocation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deliveryLocation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string delivery_location = 9;</code>
       */
      public Builder setDeliveryLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deliveryLocation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string delivery_location = 9;</code>
       */
      public Builder clearDeliveryLocation() {
        
        deliveryLocation_ = getDefaultInstance().getDeliveryLocation();
        onChanged();
        return this;
      }
      /**
       * <code>optional string delivery_location = 9;</code>
       */
      public Builder setDeliveryLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deliveryLocation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>optional string phone = 10;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string phone = 10;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phone = 10;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 10;</code>
       */
      public Builder clearPhone() {
        
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 10;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phone_ = value;
        onChanged();
        return this;
      }

      private boolean canceled_ ;
      /**
       * <code>optional bool canceled = 11;</code>
       */
      public boolean getCanceled() {
        return canceled_;
      }
      /**
       * <code>optional bool canceled = 11;</code>
       */
      public Builder setCanceled(boolean value) {
        
        canceled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool canceled = 11;</code>
       */
      public Builder clearCanceled() {
        
        canceled_ = false;
        onChanged();
        return this;
      }

      private boolean delivered_ ;
      /**
       * <code>optional bool delivered = 12;</code>
       */
      public boolean getDelivered() {
        return delivered_;
      }
      /**
       * <code>optional bool delivered = 12;</code>
       */
      public Builder setDelivered(boolean value) {
        
        delivered_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool delivered = 12;</code>
       */
      public Builder clearDelivered() {
        
        delivered_ = false;
        onChanged();
        return this;
      }

      private java.util.List<com.feedr.protobuf.FoodProto.Food> foodMap_ =
        java.util.Collections.emptyList();
      private void ensureFoodMapIsMutable() {
        if (!((bitField0_ & 0x00001000) == 0x00001000)) {
          foodMap_ = new java.util.ArrayList<com.feedr.protobuf.FoodProto.Food>(foodMap_);
          bitField0_ |= 0x00001000;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.feedr.protobuf.FoodProto.Food, com.feedr.protobuf.FoodProto.Food.Builder, com.feedr.protobuf.FoodProto.FoodOrBuilder> foodMapBuilder_;

      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public java.util.List<com.feedr.protobuf.FoodProto.Food> getFoodMapList() {
        if (foodMapBuilder_ == null) {
          return java.util.Collections.unmodifiableList(foodMap_);
        } else {
          return foodMapBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public int getFoodMapCount() {
        if (foodMapBuilder_ == null) {
          return foodMap_.size();
        } else {
          return foodMapBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public com.feedr.protobuf.FoodProto.Food getFoodMap(int index) {
        if (foodMapBuilder_ == null) {
          return foodMap_.get(index);
        } else {
          return foodMapBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public Builder setFoodMap(
          int index, com.feedr.protobuf.FoodProto.Food value) {
        if (foodMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFoodMapIsMutable();
          foodMap_.set(index, value);
          onChanged();
        } else {
          foodMapBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public Builder setFoodMap(
          int index, com.feedr.protobuf.FoodProto.Food.Builder builderForValue) {
        if (foodMapBuilder_ == null) {
          ensureFoodMapIsMutable();
          foodMap_.set(index, builderForValue.build());
          onChanged();
        } else {
          foodMapBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public Builder addFoodMap(com.feedr.protobuf.FoodProto.Food value) {
        if (foodMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFoodMapIsMutable();
          foodMap_.add(value);
          onChanged();
        } else {
          foodMapBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public Builder addFoodMap(
          int index, com.feedr.protobuf.FoodProto.Food value) {
        if (foodMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFoodMapIsMutable();
          foodMap_.add(index, value);
          onChanged();
        } else {
          foodMapBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public Builder addFoodMap(
          com.feedr.protobuf.FoodProto.Food.Builder builderForValue) {
        if (foodMapBuilder_ == null) {
          ensureFoodMapIsMutable();
          foodMap_.add(builderForValue.build());
          onChanged();
        } else {
          foodMapBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public Builder addFoodMap(
          int index, com.feedr.protobuf.FoodProto.Food.Builder builderForValue) {
        if (foodMapBuilder_ == null) {
          ensureFoodMapIsMutable();
          foodMap_.add(index, builderForValue.build());
          onChanged();
        } else {
          foodMapBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public Builder addAllFoodMap(
          java.lang.Iterable<? extends com.feedr.protobuf.FoodProto.Food> values) {
        if (foodMapBuilder_ == null) {
          ensureFoodMapIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, foodMap_);
          onChanged();
        } else {
          foodMapBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public Builder clearFoodMap() {
        if (foodMapBuilder_ == null) {
          foodMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00001000);
          onChanged();
        } else {
          foodMapBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public Builder removeFoodMap(int index) {
        if (foodMapBuilder_ == null) {
          ensureFoodMapIsMutable();
          foodMap_.remove(index);
          onChanged();
        } else {
          foodMapBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public com.feedr.protobuf.FoodProto.Food.Builder getFoodMapBuilder(
          int index) {
        return getFoodMapFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public com.feedr.protobuf.FoodProto.FoodOrBuilder getFoodMapOrBuilder(
          int index) {
        if (foodMapBuilder_ == null) {
          return foodMap_.get(index);  } else {
          return foodMapBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public java.util.List<? extends com.feedr.protobuf.FoodProto.FoodOrBuilder> 
           getFoodMapOrBuilderList() {
        if (foodMapBuilder_ != null) {
          return foodMapBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(foodMap_);
        }
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public com.feedr.protobuf.FoodProto.Food.Builder addFoodMapBuilder() {
        return getFoodMapFieldBuilder().addBuilder(
            com.feedr.protobuf.FoodProto.Food.getDefaultInstance());
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public com.feedr.protobuf.FoodProto.Food.Builder addFoodMapBuilder(
          int index) {
        return getFoodMapFieldBuilder().addBuilder(
            index, com.feedr.protobuf.FoodProto.Food.getDefaultInstance());
      }
      /**
       * <code>repeated .Food foodMap = 13;</code>
       */
      public java.util.List<com.feedr.protobuf.FoodProto.Food.Builder> 
           getFoodMapBuilderList() {
        return getFoodMapFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.feedr.protobuf.FoodProto.Food, com.feedr.protobuf.FoodProto.Food.Builder, com.feedr.protobuf.FoodProto.FoodOrBuilder> 
          getFoodMapFieldBuilder() {
        if (foodMapBuilder_ == null) {
          foodMapBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.feedr.protobuf.FoodProto.Food, com.feedr.protobuf.FoodProto.Food.Builder, com.feedr.protobuf.FoodProto.FoodOrBuilder>(
                  foodMap_,
                  ((bitField0_ & 0x00001000) == 0x00001000),
                  getParentForChildren(),
                  isClean());
          foodMap_ = null;
        }
        return foodMapBuilder_;
      }

      private java.lang.Object cancelReason_ = "";
      /**
       * <code>optional string cancelReason = 14;</code>
       */
      public java.lang.String getCancelReason() {
        java.lang.Object ref = cancelReason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cancelReason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cancelReason = 14;</code>
       */
      public com.google.protobuf.ByteString
          getCancelReasonBytes() {
        java.lang.Object ref = cancelReason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cancelReason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cancelReason = 14;</code>
       */
      public Builder setCancelReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cancelReason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cancelReason = 14;</code>
       */
      public Builder clearCancelReason() {
        
        cancelReason_ = getDefaultInstance().getCancelReason();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cancelReason = 14;</code>
       */
      public Builder setCancelReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cancelReason_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Order)
    }

    // @@protoc_insertion_point(class_scope:Order)
    private static final com.feedr.protobuf.OrderProto.Order DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.feedr.protobuf.OrderProto.Order();
    }

    public static com.feedr.protobuf.OrderProto.Order getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Order>
        PARSER = new com.google.protobuf.AbstractParser<Order>() {
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Order(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Order> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    public com.feedr.protobuf.OrderProto.Order getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrderListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OrderList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Order orders = 1;</code>
     */
    java.util.List<com.feedr.protobuf.OrderProto.Order> 
        getOrdersList();
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    com.feedr.protobuf.OrderProto.Order getOrders(int index);
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    int getOrdersCount();
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    java.util.List<? extends com.feedr.protobuf.OrderProto.OrderOrBuilder> 
        getOrdersOrBuilderList();
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    com.feedr.protobuf.OrderProto.OrderOrBuilder getOrdersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code OrderList}
   */
  public  static final class OrderList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OrderList)
      OrderListOrBuilder {
    // Use OrderList.newBuilder() to construct.
    private OrderList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderList() {
      orders_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OrderList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                orders_ = new java.util.ArrayList<com.feedr.protobuf.OrderProto.Order>();
                mutable_bitField0_ |= 0x00000001;
              }
              orders_.add(
                  input.readMessage(com.feedr.protobuf.OrderProto.Order.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          orders_ = java.util.Collections.unmodifiableList(orders_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.feedr.protobuf.OrderProto.internal_static_OrderList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.feedr.protobuf.OrderProto.internal_static_OrderList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.feedr.protobuf.OrderProto.OrderList.class, com.feedr.protobuf.OrderProto.OrderList.Builder.class);
    }

    public static final int ORDERS_FIELD_NUMBER = 1;
    private java.util.List<com.feedr.protobuf.OrderProto.Order> orders_;
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    public java.util.List<com.feedr.protobuf.OrderProto.Order> getOrdersList() {
      return orders_;
    }
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    public java.util.List<? extends com.feedr.protobuf.OrderProto.OrderOrBuilder> 
        getOrdersOrBuilderList() {
      return orders_;
    }
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    public int getOrdersCount() {
      return orders_.size();
    }
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    public com.feedr.protobuf.OrderProto.Order getOrders(int index) {
      return orders_.get(index);
    }
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    public com.feedr.protobuf.OrderProto.OrderOrBuilder getOrdersOrBuilder(
        int index) {
      return orders_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < orders_.size(); i++) {
        output.writeMessage(1, orders_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < orders_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, orders_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.feedr.protobuf.OrderProto.OrderList)) {
        return super.equals(obj);
      }
      com.feedr.protobuf.OrderProto.OrderList other = (com.feedr.protobuf.OrderProto.OrderList) obj;

      boolean result = true;
      result = result && getOrdersList()
          .equals(other.getOrdersList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getOrdersCount() > 0) {
        hash = (37 * hash) + ORDERS_FIELD_NUMBER;
        hash = (53 * hash) + getOrdersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.feedr.protobuf.OrderProto.OrderList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feedr.protobuf.OrderProto.OrderList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feedr.protobuf.OrderProto.OrderList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feedr.protobuf.OrderProto.OrderList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feedr.protobuf.OrderProto.OrderList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.OrderProto.OrderList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feedr.protobuf.OrderProto.OrderList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.OrderProto.OrderList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feedr.protobuf.OrderProto.OrderList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.OrderProto.OrderList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.feedr.protobuf.OrderProto.OrderList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OrderList)
        com.feedr.protobuf.OrderProto.OrderListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.feedr.protobuf.OrderProto.internal_static_OrderList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.feedr.protobuf.OrderProto.internal_static_OrderList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.feedr.protobuf.OrderProto.OrderList.class, com.feedr.protobuf.OrderProto.OrderList.Builder.class);
      }

      // Construct using com.feedr.protobuf.OrderProto.OrderList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOrdersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (ordersBuilder_ == null) {
          orders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ordersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.feedr.protobuf.OrderProto.internal_static_OrderList_descriptor;
      }

      public com.feedr.protobuf.OrderProto.OrderList getDefaultInstanceForType() {
        return com.feedr.protobuf.OrderProto.OrderList.getDefaultInstance();
      }

      public com.feedr.protobuf.OrderProto.OrderList build() {
        com.feedr.protobuf.OrderProto.OrderList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.feedr.protobuf.OrderProto.OrderList buildPartial() {
        com.feedr.protobuf.OrderProto.OrderList result = new com.feedr.protobuf.OrderProto.OrderList(this);
        int from_bitField0_ = bitField0_;
        if (ordersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            orders_ = java.util.Collections.unmodifiableList(orders_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.orders_ = orders_;
        } else {
          result.orders_ = ordersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.feedr.protobuf.OrderProto.OrderList) {
          return mergeFrom((com.feedr.protobuf.OrderProto.OrderList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.feedr.protobuf.OrderProto.OrderList other) {
        if (other == com.feedr.protobuf.OrderProto.OrderList.getDefaultInstance()) return this;
        if (ordersBuilder_ == null) {
          if (!other.orders_.isEmpty()) {
            if (orders_.isEmpty()) {
              orders_ = other.orders_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOrdersIsMutable();
              orders_.addAll(other.orders_);
            }
            onChanged();
          }
        } else {
          if (!other.orders_.isEmpty()) {
            if (ordersBuilder_.isEmpty()) {
              ordersBuilder_.dispose();
              ordersBuilder_ = null;
              orders_ = other.orders_;
              bitField0_ = (bitField0_ & ~0x00000001);
              ordersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOrdersFieldBuilder() : null;
            } else {
              ordersBuilder_.addAllMessages(other.orders_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.feedr.protobuf.OrderProto.OrderList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.feedr.protobuf.OrderProto.OrderList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.feedr.protobuf.OrderProto.Order> orders_ =
        java.util.Collections.emptyList();
      private void ensureOrdersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          orders_ = new java.util.ArrayList<com.feedr.protobuf.OrderProto.Order>(orders_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.feedr.protobuf.OrderProto.Order, com.feedr.protobuf.OrderProto.Order.Builder, com.feedr.protobuf.OrderProto.OrderOrBuilder> ordersBuilder_;

      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public java.util.List<com.feedr.protobuf.OrderProto.Order> getOrdersList() {
        if (ordersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orders_);
        } else {
          return ordersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public int getOrdersCount() {
        if (ordersBuilder_ == null) {
          return orders_.size();
        } else {
          return ordersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.feedr.protobuf.OrderProto.Order getOrders(int index) {
        if (ordersBuilder_ == null) {
          return orders_.get(index);
        } else {
          return ordersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder setOrders(
          int index, com.feedr.protobuf.OrderProto.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.set(index, value);
          onChanged();
        } else {
          ordersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder setOrders(
          int index, com.feedr.protobuf.OrderProto.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.set(index, builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addOrders(com.feedr.protobuf.OrderProto.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.add(value);
          onChanged();
        } else {
          ordersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addOrders(
          int index, com.feedr.protobuf.OrderProto.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.add(index, value);
          onChanged();
        } else {
          ordersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addOrders(
          com.feedr.protobuf.OrderProto.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.add(builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addOrders(
          int index, com.feedr.protobuf.OrderProto.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.add(index, builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addAllOrders(
          java.lang.Iterable<? extends com.feedr.protobuf.OrderProto.Order> values) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, orders_);
          onChanged();
        } else {
          ordersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder clearOrders() {
        if (ordersBuilder_ == null) {
          orders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          ordersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder removeOrders(int index) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.remove(index);
          onChanged();
        } else {
          ordersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.feedr.protobuf.OrderProto.Order.Builder getOrdersBuilder(
          int index) {
        return getOrdersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.feedr.protobuf.OrderProto.OrderOrBuilder getOrdersOrBuilder(
          int index) {
        if (ordersBuilder_ == null) {
          return orders_.get(index);  } else {
          return ordersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public java.util.List<? extends com.feedr.protobuf.OrderProto.OrderOrBuilder> 
           getOrdersOrBuilderList() {
        if (ordersBuilder_ != null) {
          return ordersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orders_);
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.feedr.protobuf.OrderProto.Order.Builder addOrdersBuilder() {
        return getOrdersFieldBuilder().addBuilder(
            com.feedr.protobuf.OrderProto.Order.getDefaultInstance());
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.feedr.protobuf.OrderProto.Order.Builder addOrdersBuilder(
          int index) {
        return getOrdersFieldBuilder().addBuilder(
            index, com.feedr.protobuf.OrderProto.Order.getDefaultInstance());
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public java.util.List<com.feedr.protobuf.OrderProto.Order.Builder> 
           getOrdersBuilderList() {
        return getOrdersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.feedr.protobuf.OrderProto.Order, com.feedr.protobuf.OrderProto.Order.Builder, com.feedr.protobuf.OrderProto.OrderOrBuilder> 
          getOrdersFieldBuilder() {
        if (ordersBuilder_ == null) {
          ordersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.feedr.protobuf.OrderProto.Order, com.feedr.protobuf.OrderProto.Order.Builder, com.feedr.protobuf.OrderProto.OrderOrBuilder>(
                  orders_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          orders_ = null;
        }
        return ordersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:OrderList)
    }

    // @@protoc_insertion_point(class_scope:OrderList)
    private static final com.feedr.protobuf.OrderProto.OrderList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.feedr.protobuf.OrderProto.OrderList();
    }

    public static com.feedr.protobuf.OrderProto.OrderList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderList>
        PARSER = new com.google.protobuf.AbstractParser<OrderList>() {
      public OrderList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OrderList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderList> getParserForType() {
      return PARSER;
    }

    public com.feedr.protobuf.OrderProto.OrderList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Order_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Order.proto\032\020Restaurant.proto\"\252\002\n\005Orde" +
      "r\022\020\n\010order_id\030\001 \001(\005\022\023\n\013sender_name\030\002 \001(\t" +
      "\022\025\n\rreceiver_name\030\003 \001(\t\022\027\n\017restaurant_na" +
      "me\030\004 \001(\t\022\022\n\norder_cost\030\005 \001(\001\022\023\n\013deliver_" +
      "tip\030\006 \001(\001\022\022\n\norder_time\030\007 \001(\t\022\020\n\010deadlin" +
      "e\030\010 \001(\t\022\031\n\021delivery_location\030\t \001(\t\022\r\n\005ph" +
      "one\030\n \001(\t\022\020\n\010canceled\030\013 \001(\010\022\021\n\tdelivered" +
      "\030\014 \001(\010\022\026\n\007foodMap\030\r \003(\0132\005.Food\022\024\n\014cancel" +
      "Reason\030\016 \001(\t\"#\n\tOrderList\022\026\n\006orders\030\001 \003(" +
      "\0132\006.OrderB \n\022com.feedr.protobufB\nOrderPr",
      "otob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.feedr.protobuf.FoodProto.getDescriptor(),
        }, assigner);
    internal_static_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Order_descriptor,
        new java.lang.String[] { "OrderId", "SenderName", "ReceiverName", "RestaurantName", "OrderCost", "DeliverTip", "OrderTime", "Deadline", "DeliveryLocation", "Phone", "Canceled", "Delivered", "FoodMap", "CancelReason", });
    internal_static_OrderList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OrderList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderList_descriptor,
        new java.lang.String[] { "Orders", });
    com.feedr.protobuf.FoodProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
