// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Profile.proto

package com.feedr.protobuf;

public final class ProfileProto {
  private ProfileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProfileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Profile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional string phone = 2;</code>
     */
    java.lang.String getPhone();
    /**
     * <code>optional string phone = 2;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>optional string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional string type = 4;</code>
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 4;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional int32 sender_rating = 5;</code>
     */
    int getSenderRating();

    /**
     * <code>optional string sender_location = 6;</code>
     */
    java.lang.String getSenderLocation();
    /**
     * <code>optional string sender_location = 6;</code>
     */
    com.google.protobuf.ByteString
        getSenderLocationBytes();

    /**
     * <code>optional string res_name = 7;</code>
     */
    java.lang.String getResName();
    /**
     * <code>optional string res_name = 7;</code>
     */
    com.google.protobuf.ByteString
        getResNameBytes();

    /**
     * <code>optional int32 res_rating = 8;</code>
     */
    int getResRating();

    /**
     * <code>optional string res_location = 9;</code>
     */
    java.lang.String getResLocation();
    /**
     * <code>optional string res_location = 9;</code>
     */
    com.google.protobuf.ByteString
        getResLocationBytes();
  }
  /**
   * Protobuf type {@code Profile}
   */
  public  static final class Profile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Profile)
      ProfileOrBuilder {
    // Use Profile.newBuilder() to construct.
    private Profile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Profile() {
      username_ = "";
      phone_ = "";
      password_ = "";
      type_ = "";
      senderRating_ = 0;
      senderLocation_ = "";
      resName_ = "";
      resRating_ = 0;
      resLocation_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Profile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 40: {

              senderRating_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              senderLocation_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              resName_ = s;
              break;
            }
            case 64: {

              resRating_ = input.readInt32();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              resLocation_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.feedr.protobuf.ProfileProto.internal_static_Profile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.feedr.protobuf.ProfileProto.internal_static_Profile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.feedr.protobuf.ProfileProto.Profile.class, com.feedr.protobuf.ProfileProto.Profile.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object username_;
    /**
     * <code>optional string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 2;
    private volatile java.lang.Object phone_;
    /**
     * <code>optional string phone = 2;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>optional string phone = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object password_;
    /**
     * <code>optional string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object type_;
    /**
     * <code>optional string type = 4;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>optional string type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_RATING_FIELD_NUMBER = 5;
    private int senderRating_;
    /**
     * <code>optional int32 sender_rating = 5;</code>
     */
    public int getSenderRating() {
      return senderRating_;
    }

    public static final int SENDER_LOCATION_FIELD_NUMBER = 6;
    private volatile java.lang.Object senderLocation_;
    /**
     * <code>optional string sender_location = 6;</code>
     */
    public java.lang.String getSenderLocation() {
      java.lang.Object ref = senderLocation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderLocation_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sender_location = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSenderLocationBytes() {
      java.lang.Object ref = senderLocation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RES_NAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object resName_;
    /**
     * <code>optional string res_name = 7;</code>
     */
    public java.lang.String getResName() {
      java.lang.Object ref = resName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string res_name = 7;</code>
     */
    public com.google.protobuf.ByteString
        getResNameBytes() {
      java.lang.Object ref = resName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RES_RATING_FIELD_NUMBER = 8;
    private int resRating_;
    /**
     * <code>optional int32 res_rating = 8;</code>
     */
    public int getResRating() {
      return resRating_;
    }

    public static final int RES_LOCATION_FIELD_NUMBER = 9;
    private volatile java.lang.Object resLocation_;
    /**
     * <code>optional string res_location = 9;</code>
     */
    public java.lang.String getResLocation() {
      java.lang.Object ref = resLocation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resLocation_ = s;
        return s;
      }
    }
    /**
     * <code>optional string res_location = 9;</code>
     */
    public com.google.protobuf.ByteString
        getResLocationBytes() {
      java.lang.Object ref = resLocation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, phone_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, type_);
      }
      if (senderRating_ != 0) {
        output.writeInt32(5, senderRating_);
      }
      if (!getSenderLocationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, senderLocation_);
      }
      if (!getResNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, resName_);
      }
      if (resRating_ != 0) {
        output.writeInt32(8, resRating_);
      }
      if (!getResLocationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, resLocation_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, phone_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, type_);
      }
      if (senderRating_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, senderRating_);
      }
      if (!getSenderLocationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, senderLocation_);
      }
      if (!getResNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, resName_);
      }
      if (resRating_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, resRating_);
      }
      if (!getResLocationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, resLocation_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.feedr.protobuf.ProfileProto.Profile)) {
        return super.equals(obj);
      }
      com.feedr.protobuf.ProfileProto.Profile other = (com.feedr.protobuf.ProfileProto.Profile) obj;

      boolean result = true;
      result = result && getUsername()
          .equals(other.getUsername());
      result = result && getPhone()
          .equals(other.getPhone());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && getType()
          .equals(other.getType());
      result = result && (getSenderRating()
          == other.getSenderRating());
      result = result && getSenderLocation()
          .equals(other.getSenderLocation());
      result = result && getResName()
          .equals(other.getResName());
      result = result && (getResRating()
          == other.getResRating());
      result = result && getResLocation()
          .equals(other.getResLocation());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + SENDER_RATING_FIELD_NUMBER;
      hash = (53 * hash) + getSenderRating();
      hash = (37 * hash) + SENDER_LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getSenderLocation().hashCode();
      hash = (37 * hash) + RES_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getResName().hashCode();
      hash = (37 * hash) + RES_RATING_FIELD_NUMBER;
      hash = (53 * hash) + getResRating();
      hash = (37 * hash) + RES_LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getResLocation().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.feedr.protobuf.ProfileProto.Profile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feedr.protobuf.ProfileProto.Profile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feedr.protobuf.ProfileProto.Profile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feedr.protobuf.ProfileProto.Profile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feedr.protobuf.ProfileProto.Profile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.ProfileProto.Profile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feedr.protobuf.ProfileProto.Profile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.ProfileProto.Profile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feedr.protobuf.ProfileProto.Profile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.ProfileProto.Profile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.feedr.protobuf.ProfileProto.Profile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Profile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Profile)
        com.feedr.protobuf.ProfileProto.ProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.feedr.protobuf.ProfileProto.internal_static_Profile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.feedr.protobuf.ProfileProto.internal_static_Profile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.feedr.protobuf.ProfileProto.Profile.class, com.feedr.protobuf.ProfileProto.Profile.Builder.class);
      }

      // Construct using com.feedr.protobuf.ProfileProto.Profile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        username_ = "";

        phone_ = "";

        password_ = "";

        type_ = "";

        senderRating_ = 0;

        senderLocation_ = "";

        resName_ = "";

        resRating_ = 0;

        resLocation_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.feedr.protobuf.ProfileProto.internal_static_Profile_descriptor;
      }

      public com.feedr.protobuf.ProfileProto.Profile getDefaultInstanceForType() {
        return com.feedr.protobuf.ProfileProto.Profile.getDefaultInstance();
      }

      public com.feedr.protobuf.ProfileProto.Profile build() {
        com.feedr.protobuf.ProfileProto.Profile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.feedr.protobuf.ProfileProto.Profile buildPartial() {
        com.feedr.protobuf.ProfileProto.Profile result = new com.feedr.protobuf.ProfileProto.Profile(this);
        result.username_ = username_;
        result.phone_ = phone_;
        result.password_ = password_;
        result.type_ = type_;
        result.senderRating_ = senderRating_;
        result.senderLocation_ = senderLocation_;
        result.resName_ = resName_;
        result.resRating_ = resRating_;
        result.resLocation_ = resLocation_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.feedr.protobuf.ProfileProto.Profile) {
          return mergeFrom((com.feedr.protobuf.ProfileProto.Profile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.feedr.protobuf.ProfileProto.Profile other) {
        if (other == com.feedr.protobuf.ProfileProto.Profile.getDefaultInstance()) return this;
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getSenderRating() != 0) {
          setSenderRating(other.getSenderRating());
        }
        if (!other.getSenderLocation().isEmpty()) {
          senderLocation_ = other.senderLocation_;
          onChanged();
        }
        if (!other.getResName().isEmpty()) {
          resName_ = other.resName_;
          onChanged();
        }
        if (other.getResRating() != 0) {
          setResRating(other.getResRating());
        }
        if (!other.getResLocation().isEmpty()) {
          resLocation_ = other.resLocation_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.feedr.protobuf.ProfileProto.Profile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.feedr.protobuf.ProfileProto.Profile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 1;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>optional string phone = 2;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string phone = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phone = 2;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 2;</code>
       */
      public Builder clearPhone() {
        
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 2;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 4;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 4;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 4;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private int senderRating_ ;
      /**
       * <code>optional int32 sender_rating = 5;</code>
       */
      public int getSenderRating() {
        return senderRating_;
      }
      /**
       * <code>optional int32 sender_rating = 5;</code>
       */
      public Builder setSenderRating(int value) {
        
        senderRating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sender_rating = 5;</code>
       */
      public Builder clearSenderRating() {
        
        senderRating_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object senderLocation_ = "";
      /**
       * <code>optional string sender_location = 6;</code>
       */
      public java.lang.String getSenderLocation() {
        java.lang.Object ref = senderLocation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderLocation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sender_location = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSenderLocationBytes() {
        java.lang.Object ref = senderLocation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderLocation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sender_location = 6;</code>
       */
      public Builder setSenderLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderLocation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sender_location = 6;</code>
       */
      public Builder clearSenderLocation() {
        
        senderLocation_ = getDefaultInstance().getSenderLocation();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sender_location = 6;</code>
       */
      public Builder setSenderLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderLocation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resName_ = "";
      /**
       * <code>optional string res_name = 7;</code>
       */
      public java.lang.String getResName() {
        java.lang.Object ref = resName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string res_name = 7;</code>
       */
      public com.google.protobuf.ByteString
          getResNameBytes() {
        java.lang.Object ref = resName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string res_name = 7;</code>
       */
      public Builder setResName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string res_name = 7;</code>
       */
      public Builder clearResName() {
        
        resName_ = getDefaultInstance().getResName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string res_name = 7;</code>
       */
      public Builder setResNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resName_ = value;
        onChanged();
        return this;
      }

      private int resRating_ ;
      /**
       * <code>optional int32 res_rating = 8;</code>
       */
      public int getResRating() {
        return resRating_;
      }
      /**
       * <code>optional int32 res_rating = 8;</code>
       */
      public Builder setResRating(int value) {
        
        resRating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 res_rating = 8;</code>
       */
      public Builder clearResRating() {
        
        resRating_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object resLocation_ = "";
      /**
       * <code>optional string res_location = 9;</code>
       */
      public java.lang.String getResLocation() {
        java.lang.Object ref = resLocation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resLocation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string res_location = 9;</code>
       */
      public com.google.protobuf.ByteString
          getResLocationBytes() {
        java.lang.Object ref = resLocation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resLocation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string res_location = 9;</code>
       */
      public Builder setResLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resLocation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string res_location = 9;</code>
       */
      public Builder clearResLocation() {
        
        resLocation_ = getDefaultInstance().getResLocation();
        onChanged();
        return this;
      }
      /**
       * <code>optional string res_location = 9;</code>
       */
      public Builder setResLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resLocation_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Profile)
    }

    // @@protoc_insertion_point(class_scope:Profile)
    private static final com.feedr.protobuf.ProfileProto.Profile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.feedr.protobuf.ProfileProto.Profile();
    }

    public static com.feedr.protobuf.ProfileProto.Profile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Profile>
        PARSER = new com.google.protobuf.AbstractParser<Profile>() {
      public Profile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Profile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Profile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Profile> getParserForType() {
      return PARSER;
    }

    public com.feedr.protobuf.ProfileProto.Profile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Profile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Profile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rProfile.proto\"\266\001\n\007Profile\022\020\n\010username\030" +
      "\001 \001(\t\022\r\n\005phone\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\014" +
      "\n\004type\030\004 \001(\t\022\025\n\rsender_rating\030\005 \001(\005\022\027\n\017s" +
      "ender_location\030\006 \001(\t\022\020\n\010res_name\030\007 \001(\t\022\022" +
      "\n\nres_rating\030\010 \001(\005\022\024\n\014res_location\030\t \001(\t" +
      "B\"\n\022com.feedr.protobufB\014ProfileProtob\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Profile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Profile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Profile_descriptor,
        new java.lang.String[] { "Username", "Phone", "Password", "Type", "SenderRating", "SenderLocation", "ResName", "ResRating", "ResLocation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
