// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rating.proto

package com.feedr.protobuf;

public final class RatingProto {
  private RatingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RatingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Rating)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 orderId = 1;</code>
     */
    int getOrderId();

    /**
     * <code>optional int32 senderRating = 2;</code>
     */
    int getSenderRating();

    /**
     * <code>optional int32 restaurantRating = 3;</code>
     */
    int getRestaurantRating();

    /**
     * <code>optional string commentSender = 4;</code>
     */
    java.lang.String getCommentSender();
    /**
     * <code>optional string commentSender = 4;</code>
     */
    com.google.protobuf.ByteString
        getCommentSenderBytes();

    /**
     * <code>optional string commentRestaurant = 5;</code>
     */
    java.lang.String getCommentRestaurant();
    /**
     * <code>optional string commentRestaurant = 5;</code>
     */
    com.google.protobuf.ByteString
        getCommentRestaurantBytes();
  }
  /**
   * Protobuf type {@code Rating}
   */
  public  static final class Rating extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Rating)
      RatingOrBuilder {
    // Use Rating.newBuilder() to construct.
    private Rating(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rating() {
      orderId_ = 0;
      senderRating_ = 0;
      restaurantRating_ = 0;
      commentSender_ = "";
      commentRestaurant_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Rating(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              orderId_ = input.readInt32();
              break;
            }
            case 16: {

              senderRating_ = input.readInt32();
              break;
            }
            case 24: {

              restaurantRating_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              commentSender_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              commentRestaurant_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.feedr.protobuf.RatingProto.internal_static_Rating_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.feedr.protobuf.RatingProto.internal_static_Rating_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.feedr.protobuf.RatingProto.Rating.class, com.feedr.protobuf.RatingProto.Rating.Builder.class);
    }

    public static final int ORDERID_FIELD_NUMBER = 1;
    private int orderId_;
    /**
     * <code>optional int32 orderId = 1;</code>
     */
    public int getOrderId() {
      return orderId_;
    }

    public static final int SENDERRATING_FIELD_NUMBER = 2;
    private int senderRating_;
    /**
     * <code>optional int32 senderRating = 2;</code>
     */
    public int getSenderRating() {
      return senderRating_;
    }

    public static final int RESTAURANTRATING_FIELD_NUMBER = 3;
    private int restaurantRating_;
    /**
     * <code>optional int32 restaurantRating = 3;</code>
     */
    public int getRestaurantRating() {
      return restaurantRating_;
    }

    public static final int COMMENTSENDER_FIELD_NUMBER = 4;
    private volatile java.lang.Object commentSender_;
    /**
     * <code>optional string commentSender = 4;</code>
     */
    public java.lang.String getCommentSender() {
      java.lang.Object ref = commentSender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commentSender_ = s;
        return s;
      }
    }
    /**
     * <code>optional string commentSender = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCommentSenderBytes() {
      java.lang.Object ref = commentSender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commentSender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMENTRESTAURANT_FIELD_NUMBER = 5;
    private volatile java.lang.Object commentRestaurant_;
    /**
     * <code>optional string commentRestaurant = 5;</code>
     */
    public java.lang.String getCommentRestaurant() {
      java.lang.Object ref = commentRestaurant_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commentRestaurant_ = s;
        return s;
      }
    }
    /**
     * <code>optional string commentRestaurant = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCommentRestaurantBytes() {
      java.lang.Object ref = commentRestaurant_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commentRestaurant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (orderId_ != 0) {
        output.writeInt32(1, orderId_);
      }
      if (senderRating_ != 0) {
        output.writeInt32(2, senderRating_);
      }
      if (restaurantRating_ != 0) {
        output.writeInt32(3, restaurantRating_);
      }
      if (!getCommentSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, commentSender_);
      }
      if (!getCommentRestaurantBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, commentRestaurant_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (orderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, orderId_);
      }
      if (senderRating_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, senderRating_);
      }
      if (restaurantRating_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, restaurantRating_);
      }
      if (!getCommentSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, commentSender_);
      }
      if (!getCommentRestaurantBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, commentRestaurant_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.feedr.protobuf.RatingProto.Rating)) {
        return super.equals(obj);
      }
      com.feedr.protobuf.RatingProto.Rating other = (com.feedr.protobuf.RatingProto.Rating) obj;

      boolean result = true;
      result = result && (getOrderId()
          == other.getOrderId());
      result = result && (getSenderRating()
          == other.getSenderRating());
      result = result && (getRestaurantRating()
          == other.getRestaurantRating());
      result = result && getCommentSender()
          .equals(other.getCommentSender());
      result = result && getCommentRestaurant()
          .equals(other.getCommentRestaurant());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId();
      hash = (37 * hash) + SENDERRATING_FIELD_NUMBER;
      hash = (53 * hash) + getSenderRating();
      hash = (37 * hash) + RESTAURANTRATING_FIELD_NUMBER;
      hash = (53 * hash) + getRestaurantRating();
      hash = (37 * hash) + COMMENTSENDER_FIELD_NUMBER;
      hash = (53 * hash) + getCommentSender().hashCode();
      hash = (37 * hash) + COMMENTRESTAURANT_FIELD_NUMBER;
      hash = (53 * hash) + getCommentRestaurant().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.feedr.protobuf.RatingProto.Rating parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feedr.protobuf.RatingProto.Rating parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feedr.protobuf.RatingProto.Rating parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feedr.protobuf.RatingProto.Rating parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feedr.protobuf.RatingProto.Rating parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.RatingProto.Rating parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feedr.protobuf.RatingProto.Rating parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.RatingProto.Rating parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feedr.protobuf.RatingProto.Rating parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feedr.protobuf.RatingProto.Rating parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.feedr.protobuf.RatingProto.Rating prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Rating}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Rating)
        com.feedr.protobuf.RatingProto.RatingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.feedr.protobuf.RatingProto.internal_static_Rating_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.feedr.protobuf.RatingProto.internal_static_Rating_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.feedr.protobuf.RatingProto.Rating.class, com.feedr.protobuf.RatingProto.Rating.Builder.class);
      }

      // Construct using com.feedr.protobuf.RatingProto.Rating.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        orderId_ = 0;

        senderRating_ = 0;

        restaurantRating_ = 0;

        commentSender_ = "";

        commentRestaurant_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.feedr.protobuf.RatingProto.internal_static_Rating_descriptor;
      }

      public com.feedr.protobuf.RatingProto.Rating getDefaultInstanceForType() {
        return com.feedr.protobuf.RatingProto.Rating.getDefaultInstance();
      }

      public com.feedr.protobuf.RatingProto.Rating build() {
        com.feedr.protobuf.RatingProto.Rating result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.feedr.protobuf.RatingProto.Rating buildPartial() {
        com.feedr.protobuf.RatingProto.Rating result = new com.feedr.protobuf.RatingProto.Rating(this);
        result.orderId_ = orderId_;
        result.senderRating_ = senderRating_;
        result.restaurantRating_ = restaurantRating_;
        result.commentSender_ = commentSender_;
        result.commentRestaurant_ = commentRestaurant_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.feedr.protobuf.RatingProto.Rating) {
          return mergeFrom((com.feedr.protobuf.RatingProto.Rating)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.feedr.protobuf.RatingProto.Rating other) {
        if (other == com.feedr.protobuf.RatingProto.Rating.getDefaultInstance()) return this;
        if (other.getOrderId() != 0) {
          setOrderId(other.getOrderId());
        }
        if (other.getSenderRating() != 0) {
          setSenderRating(other.getSenderRating());
        }
        if (other.getRestaurantRating() != 0) {
          setRestaurantRating(other.getRestaurantRating());
        }
        if (!other.getCommentSender().isEmpty()) {
          commentSender_ = other.commentSender_;
          onChanged();
        }
        if (!other.getCommentRestaurant().isEmpty()) {
          commentRestaurant_ = other.commentRestaurant_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.feedr.protobuf.RatingProto.Rating parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.feedr.protobuf.RatingProto.Rating) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int orderId_ ;
      /**
       * <code>optional int32 orderId = 1;</code>
       */
      public int getOrderId() {
        return orderId_;
      }
      /**
       * <code>optional int32 orderId = 1;</code>
       */
      public Builder setOrderId(int value) {
        
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 orderId = 1;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = 0;
        onChanged();
        return this;
      }

      private int senderRating_ ;
      /**
       * <code>optional int32 senderRating = 2;</code>
       */
      public int getSenderRating() {
        return senderRating_;
      }
      /**
       * <code>optional int32 senderRating = 2;</code>
       */
      public Builder setSenderRating(int value) {
        
        senderRating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 senderRating = 2;</code>
       */
      public Builder clearSenderRating() {
        
        senderRating_ = 0;
        onChanged();
        return this;
      }

      private int restaurantRating_ ;
      /**
       * <code>optional int32 restaurantRating = 3;</code>
       */
      public int getRestaurantRating() {
        return restaurantRating_;
      }
      /**
       * <code>optional int32 restaurantRating = 3;</code>
       */
      public Builder setRestaurantRating(int value) {
        
        restaurantRating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 restaurantRating = 3;</code>
       */
      public Builder clearRestaurantRating() {
        
        restaurantRating_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object commentSender_ = "";
      /**
       * <code>optional string commentSender = 4;</code>
       */
      public java.lang.String getCommentSender() {
        java.lang.Object ref = commentSender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commentSender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string commentSender = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCommentSenderBytes() {
        java.lang.Object ref = commentSender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commentSender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string commentSender = 4;</code>
       */
      public Builder setCommentSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commentSender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string commentSender = 4;</code>
       */
      public Builder clearCommentSender() {
        
        commentSender_ = getDefaultInstance().getCommentSender();
        onChanged();
        return this;
      }
      /**
       * <code>optional string commentSender = 4;</code>
       */
      public Builder setCommentSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commentSender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object commentRestaurant_ = "";
      /**
       * <code>optional string commentRestaurant = 5;</code>
       */
      public java.lang.String getCommentRestaurant() {
        java.lang.Object ref = commentRestaurant_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commentRestaurant_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string commentRestaurant = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCommentRestaurantBytes() {
        java.lang.Object ref = commentRestaurant_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commentRestaurant_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string commentRestaurant = 5;</code>
       */
      public Builder setCommentRestaurant(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commentRestaurant_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string commentRestaurant = 5;</code>
       */
      public Builder clearCommentRestaurant() {
        
        commentRestaurant_ = getDefaultInstance().getCommentRestaurant();
        onChanged();
        return this;
      }
      /**
       * <code>optional string commentRestaurant = 5;</code>
       */
      public Builder setCommentRestaurantBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commentRestaurant_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Rating)
    }

    // @@protoc_insertion_point(class_scope:Rating)
    private static final com.feedr.protobuf.RatingProto.Rating DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.feedr.protobuf.RatingProto.Rating();
    }

    public static com.feedr.protobuf.RatingProto.Rating getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Rating>
        PARSER = new com.google.protobuf.AbstractParser<Rating>() {
      public Rating parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Rating(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Rating> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rating> getParserForType() {
      return PARSER;
    }

    public com.feedr.protobuf.RatingProto.Rating getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Rating_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Rating_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Rating.proto\"{\n\006Rating\022\017\n\007orderId\030\001 \001(" +
      "\005\022\024\n\014senderRating\030\002 \001(\005\022\030\n\020restaurantRat" +
      "ing\030\003 \001(\005\022\025\n\rcommentSender\030\004 \001(\t\022\031\n\021comm" +
      "entRestaurant\030\005 \001(\tB!\n\022com.feedr.protobu" +
      "fB\013RatingProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Rating_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Rating_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Rating_descriptor,
        new java.lang.String[] { "OrderId", "SenderRating", "RestaurantRating", "CommentSender", "CommentRestaurant", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
